### ISSUE TITLE
Building container fails with "locale-gen not found" error

### ISSUE THREAD

**Issue by Antti** [tailhook/vagga-docker#10]
When trying to start a command, during the container build (after the image was downloaded) it fails with:
```
ERROR:vagga::builder: Error building container "fca": step Ubuntu("xenial") failed: command "locale-gen" not found in one of "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
ERROR:vagga::wrapper: Error executing _build: Builder exited with code 1
```
I think it's related to https://github.com/tailhook/vagga/issues/406

**Comment by tailhook** [comment]
Yes. We haven't upgraded vagga-docker's version of vagga for a while. Is there any reason why you want vagga-docker rather than vagga-box? The latter is used by ore people and is usually faster. You can also upgrade vagga inside a vagga-box without any effort on our side.

**Comment by Antti** [comment]
@tailhook The reason is that we already have a docker-compose based environment, which is run using docker-for-mac. It would be convenient to use an already existing setup to run vagga on top of it (using docker-compose for development is not great).

**Comment by tailhook** [comment]
Okay. Upgraded vagga image to v0.7.2. You need to upgrade vagga-docker and new image will be downloaded automatically.

**Comment by Antti** [comment]
Brilliant!
It works well now.

Thank you!
