### ISSUE TITLE
Inotify doesn't work inside vagga container in docker

### ISSUE THREAD

**Issue by a-urth** [tailhook/vagga-docker#5]
I'm running pylons (python2) project with paster in vagga container under docker for mac beta and it seems that inotify doesn't work because paster just polls all files consuming almost half of cpu resources.

latest vagga and vagga-docker
docker for mac 1.12.0-rc3-beta18

**Comment by tailhook** [comment]
It has been reported that inotify works for webpack (cc @zemlanin). So I'm not sure what is the problem.

The only way I see to debug this is to install `strace` into a container and run the application with `strace -f -s 1000 -o strace.log python`. It will be slow, but should provide enough info for me debug the issue (provide the log for me privately, as it contains sensitive data).

**Comment by a-urth** [comment]
I can confirm too that with webpack it works. But with python paster - no.

**Comment by tailhook** [comment]
Well, from a glance I don't see any inotify code in paste reloader:
https://bitbucket.org/ianb/paste/src/0e5a48796ab969d874c6b772c5c33561ac2d1b0d/paste/reloader.py

**Comment by tailhook** [comment]
So it's not an inotify issue (and not vagga-docker specific). This should be fixed in paster I think or another tool might be used for reloading python application.
