### ISSUE TITLE
Docker image with Vagga is not up-to-date

### ISSUE THREAD

**Issue by MarkLavrynenko** [tailhook/vagga-docker#7]
I can't run Vagga on Mac OS anymore because of outdated Vagga version in Docker image.

Unfortunatelly I can't build image myself because I don't have archive with Vagga https://github.com/tailhook/vagga-docker/blob/master/dockerfile/Dockerfile#L2

```
Marks-MacBook-Pro:uaprom marklavrynenko$ eval $(docker-machine env)
Marks-MacBook-Pro:uaprom marklavrynenko$ docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                                            NAMES
1b20ec28750d        tailhook/vagga:v0.6.1-44-gc32f05e   "/vagga/busybox sleep"   22 hours ago        Up 22 hours         0.0.0.0:5000->5000/tcp, 0.0.0.0:6379->6379/tcp   vagga-uaprom
Marks-MacBook-Pro:uaprom marklavrynenko$ vagga 
config: /work/vagga.yaml:11:16: Validation Error: Please upgrade vagga to at least "v0.6.1-47"
Config "/work/vagga.yaml" cannot be read: Multiple errors in configuration file /work/vagga.yaml
```

**Comment by tailhook** [comment]
I have uploaded a new image. Thanks for the report!

Just to make things more clear:

> config: /work/vagga.yaml:11:16: Validation Error: Please upgrade vagga to at least "v0.6.1-47"

This error means that this specific config can't be run on that old version of vagga. Not that you can't run vagga

> Unfortunately, I can't build image myself because I don't have archive with Vagga

The archive is [here](http://files.zerogw.com/vagga/latest-testing.html), It's a normal archive from the [installation docs](http://vagga.readthedocs.io/en/latest/installation.html). You couldn't push it anyway so it makes sense to report the issue nevertheless.
